version: "3.9"

services:
  reduos:
    build:
      context: .
      dockerfile: Dockerfile
    image: localhost/redu-os:latest
    container_name: reduos
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    restart: unless-stopped