import type { RecommendedAction } from '@/types';

export const mockActions: RecommendedAction[] = [
  {
    id: '1',
    title: 'Improve onboarding copy',
    priority: 'high',
    reason: '3 users reported confusion during SSH key setup',
    suggestedOwner: 'Product Team',
    relatedIntegration: 'zammad',
    status: 'suggested',
    estimatedTime: '2-4 hours',
  },
  {
    id: '2',
    title: 'Send newsletter to new waitlist users',
    priority: 'medium',
    reason: '156 new signups in the last 24 hours',
    suggestedOwner: 'Marketing',
    relatedIntegration: 'listmonk',
    status: 'suggested',
    estimatedTime: '30 minutes',
  },
  {
    id: '3',
    title: 'Investigate API timeout errors',
    priority: 'high',
    reason: 'Detected 5 timeout errors in the last 10 minutes',
    suggestedOwner: 'DevOps',
    relatedIntegration: 'glitchtip',
    status: 'suggested',
    estimatedTime: '1-2 hours',
  },
  {
    id: '4',
    title: 'Create Zammad ticket for SSH setup guide',
    priority: 'medium',
    reason: 'Repeated support issue about SSH key configuration',
    suggestedOwner: 'Support',
    relatedIntegration: 'zammad',
    status: 'suggested',
    estimatedTime: '20 minutes',
  },
  {
    id: '5',
    title: 'Add FAQ section for onboarding',
    priority: 'medium',
    reason: 'Support workload could be reduced with better documentation',
    suggestedOwner: 'Product/Support',
    relatedIntegration: 'qdrant',
    status: 'accepted',
    estimatedTime: '3-5 hours',
  },
  {
    id: '6',
    title: 'Run weekly founder update',
    priority: 'low',
    reason: 'Weekly summary of key metrics and events',
    suggestedOwner: 'Founder',
    relatedIntegration: 'flowise',
    status: 'done',
    estimatedTime: '15 minutes',
  },
];
