import type { Integration } from '@/types';

export const mockIntegrations: Integration[] = [
  {
    id: 'listmonk',
    name: 'Listmonk',
    category: 'newsletter',
    status: 'demo_mode',
    description: 'Waitlist and newsletter management',
    useCase: 'Manage signups, track waitlist growth, send newsletters',
    color: 'bg-blue-500',
  },
  {
    id: 'ollama',
    name: 'Ollama + DeepSeek',
    category: 'ai',
    status: 'demo_mode',
    description: 'Local private AI models',
    useCase: 'Run DeepSeek locally for startup insights and recommendations',
    color: 'bg-purple-500',
  },
  {
    id: 'activepieces',
    name: 'Activepieces',
    category: 'automation',
    status: 'demo_mode',
    description: 'No-code automation platform',
    useCase: 'Automate workflows between tools, trigger actions on events',
    color: 'bg-emerald-500',
  },
  {
    id: 'zammad',
    name: 'Zammad',
    category: 'support',
    status: 'demo_mode',
    description: 'AI-powered support ticketing',
    useCase: 'Track support issues, resolve with AI assistance',
    color: 'bg-orange-500',
  },
  {
    id: 'umami',
    name: 'Umami',
    category: 'analytics',
    status: 'demo_mode',
    description: 'Privacy-focused product analytics',
    useCase: 'Track user behavior, conversion funnels, feature adoption',
    color: 'bg-pink-500',
  },
  {
    id: 'uptime-kuma',
    name: 'Uptime Kuma',
    category: 'monitoring',
    status: 'demo_mode',
    description: 'Infrastructure monitoring and alerts',
    useCase: 'Monitor uptime, receive outage alerts',
    color: 'bg-red-500',
  },
  {
    id: 'qdrant',
    name: 'Qdrant',
    category: 'database',
    status: 'demo_mode',
    description: 'Vector database for RAG',
    useCase: 'Store embeddings, enable semantic search for docs',
    color: 'bg-cyan-500',
  },
  {
    id: 'firecrawl',
    name: 'Firecrawl',
    category: 'ai',
    status: 'demo_mode',
    description: 'Web crawler for documentation',
    useCase: 'Index websites and docs for RAG context',
    color: 'bg-yellow-500',
  },
  {
    id: 'flowise',
    name: 'Flowise',
    category: 'ai',
    status: 'demo_mode',
    description: 'Visual RAG and agent builder',
    useCase: 'Build AI agents and RAG chains visually',
    color: 'bg-violet-500',
  },
  {
    id: 'langfuse',
    name: 'Langfuse',
    category: 'ai',
    status: 'demo_mode',
    description: 'LLM observability',
    useCase: 'Monitor and debug AI workflows, track costs',
    color: 'bg-indigo-500',
  },
  {
    id: 'appwrite',
    name: 'Appwrite',
    category: 'backend',
    status: 'demo_mode',
    description: 'Backend-as-a-service platform',
    useCase: 'Backend API, auth, database, file storage',
    color: 'bg-rose-500',
  },
  {
    id: 'glitchtip',
    name: 'GlitchTip',
    category: 'errors',
    status: 'demo_mode',
    description: 'Error tracking and monitoring',
    useCase: 'Track app errors, get notified of issues',
    color: 'bg-lime-500',
  },
];
