import type { StartupEvent } from '@/types';

export const mockEvents: StartupEvent[] = [
  {
    id: '1',
    type: 'signup',
    source: 'listmonk',
    title: 'New signup from Sarah Chen',
    message: 'sarah.chen@startup.io joined the waitlist',
    priority: 'low',
    timestamp: new Date(Date.now() - 15 * 60000).toISOString(),
    metadata: { email: 'sarah.chen@startup.io', source: 'product_hunt' },
  },
  {
    id: '2',
    type: 'support',
    source: 'zammad',
    title: 'SSH key configuration issue',
    message: 'User unable to create instance due to SSH key validation error',
    priority: 'high',
    timestamp: new Date(Date.now() - 32 * 60000).toISOString(),
    metadata: { user: 'alex_kim', email: 'alex@company.com' },
  },
  {
    id: '3',
    type: 'analytics',
    source: 'umami',
    title: 'Onboarding flow conversion',
    message: '12 users completed the getting-started flow',
    priority: 'low',
    timestamp: new Date(Date.now() - 48 * 60000).toISOString(),
  },
  {
    id: '4',
    type: 'error',
    source: 'glitchtip',
    title: 'API timeout error spike',
    message: 'Detected 5 API timeout errors in the last 10 minutes',
    priority: 'high',
    timestamp: new Date(Date.now() - 62 * 60000).toISOString(),
  },
  {
    id: '5',
    type: 'ai',
    source: 'flowise',
    title: 'AI workflow completed',
    message: 'Customer support automation processed 23 tickets',
    priority: 'low',
    timestamp: new Date(Date.now() - 90 * 60000).toISOString(),
  },
  {
    id: '6',
    type: 'uptime',
    source: 'uptime-kuma',
    title: 'Brief API outage detected',
    message: 'API was unavailable for 2 minutes, now recovered',
    priority: 'high',
    timestamp: new Date(Date.now() - 120 * 60000).toISOString(),
  },
  {
    id: '7',
    type: 'rag',
    source: 'custom',
    title: 'RAG documents indexed',
    message: '15 new documentation pages indexed in vector database',
    priority: 'low',
    timestamp: new Date(Date.now() - 180 * 60000).toISOString(),
  },
  {
    id: '8',
    type: 'automation',
    source: 'activepieces',
    title: 'Newsletter sent',
    message: 'Weekly newsletter delivered to 2,458 subscribers',
    priority: 'low',
    timestamp: new Date(Date.now() - 240 * 60000).toISOString(),
  },
];
