FROM docker.io/library/python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip wheel \
  && pip install --no-cache-dir -r requirements.txt

COPY app.py .

EXPOSE 3010

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "3010"]
